## Лабораторна робота 1.
###Вступ до машинного навчання. Елементи лінійної алгебри.

Варіант 3

In [1]:
import numpy as np
import random

*деякі завдання виконувала двома способами - і суто на python, і з використанням бібліотеки numpy*

1. Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть його значення.

In [2]:
vector = np.arange(2, 21, 2)
print(vector)

[ 2  4  6  8 10 12 14 16 18 20]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.

In [3]:
matrix = [[random.random() for _ in range(3)] for _ in range(3)]

for row in matrix:
    print(row)

[0.8653664439329724, 0.5958438013761422, 0.6224807750539393]
[0.9020587581127453, 0.6044128967938109, 0.2035596357487398]
[0.9435233437623908, 0.6108016187978644, 0.7026717930953257]


In [4]:
matrix = np.random.rand(3, 3)
print(matrix)

[[0.26806737 0.26804266 0.08165298]
 [0.8063677  0.94021829 0.21833107]
 [0.64012672 0.30216244 0.66148643]]


3. Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 20 та виведіть його значення.

In [5]:
matrix = [[random.randint(1, 20) for _ in range(3)] for _ in range(3)]

for row in matrix:
    print(row)

[19, 3, 15]
[16, 10, 6]
[11, 5, 2]


In [6]:
matrix = np.random.randint(1, 21, size=(3, 3))
print(matrix)

[[13 12  8]
 [ 1  9 14]
 [ 1 20 19]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть мінімальний елемент.

In [7]:
matrix = [[random.random() for _ in range(4)] for _ in range(4)]

for row in matrix:
    print(row)

[0.9057942520612828, 0.3233200200425963, 0.28587778488765914, 0.9805111101682225]
[0.6419863620690645, 0.24658002779411192, 0.12133890013012727, 0.4443713113970995]
[0.2040922449947744, 0.2633093853524643, 0.995919494230631, 0.4208704719562506]
[0.46557481474120177, 0.2899372622781542, 0.5777563939414395, 0.6022275823087008]


In [8]:
min_value = min(min(row) for row in matrix)
print("Мінімальний елемент:", min_value)

Мінімальний елемент: 0.12133890013012727


In [9]:
matrix = np.random.rand(4, 4)
print(matrix)

[[0.04003459 0.63464832 0.00550449 0.25229669]
 [0.26800635 0.59914421 0.29507137 0.3075614 ]
 [0.92236088 0.84635592 0.71772569 0.39816168]
 [0.76800684 0.49665951 0.67641227 0.61237511]]


In [10]:
min_value = np.min(matrix)
print("Мінімальний елемент:", min_value)

Мінімальний елемент: 0.005504493697042978


5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.

In [11]:
array1 = np.random.randint(1, 16, size=7)
array2 = np.random.randint(1, 16, size=7)

In [12]:
print(array1)

[ 7  7 15 15  7  4  3]


In [13]:
print(array2)

[ 7  4  8  4  2  3 13]


In [14]:
addition = array1 + array2
print("Результат додавання:", addition)

subtraction = array1 - array2
print("Результат віднімання:", subtraction)

multiplication = array1 * array2
print("Результат множення:", multiplication)

Результат додавання: [14 11 23 19  9  7 16]
Результат віднімання: [  0   3   7  11   5   1 -10]
Результат множення: [ 49  28 120  60  14  12  39]


6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та знайдіть їх добуток.

In [15]:
matrix1 = np.random.randint(3, 31, size=(3, 3))

print("Матриця 1:")
print(matrix1)


matrix2 = np.random.randint(3, 31, size=(3, 3))

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[10 10 25]
 [12 28 13]
 [24  4 22]]

Матриця 2:
[[ 8 29 18]
 [29 19 23]
 [29 13 25]]


In [16]:
result = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(result)

Добуток матриць:
[[1095  805 1035]
 [1285 1049 1185]
 [ 946 1058 1074]]


7. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 7 та перемножте їх між собою.

In [17]:
matrix1 = np.random.randint(1, 8, size=(4, 2))
matrix2 = np.random.randint(1, 8, size=(2, 5))

result = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nДобуток матриць:")
print(result)

Матриця 1:
[[7 1]
 [3 6]
 [2 3]
 [3 1]]

Матриця 2:
[[6 4 6 7 5]
 [6 6 6 4 2]]

Добуток матриць:
[[48 34 48 53 37]
 [54 48 54 45 27]
 [30 26 30 26 16]
 [24 18 24 25 17]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю

In [18]:
matrix = np.random.randint(1, 9, size=(2, 2))
inverse_matrix = np.linalg.inv(matrix)

print("Початкова матриця:")
print(matrix)

print("\nОбернена матриця:")
print(inverse_matrix)

Початкова матриця:
[[4 6]
 [4 8]]

Обернена матриця:
[[ 1.   -0.75]
 [-0.5   0.5 ]]


9. Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [19]:
matrix = np.random.rand(2, 3)
transposed_matrix = np.transpose(matrix)

print("Початкова матриця:")
print(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[0.18024918 0.70093262 0.53755765]
 [0.04880587 0.11028308 0.67571104]]

Транспонована матриця:
[[0.18024918 0.04880587]
 [0.70093262 0.11028308]
 [0.53755765 0.67571104]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

In [20]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[5 3 8 2]
 [5 7 6 9]
 [8 8 5 7]]

Вектор:
[[ 7]
 [ 8]
 [10]
 [ 4]]

Добуток матриці на вектор:
[[147]
 [187]
 [198]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [21]:
matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, size=(3, 1))
product = np.dot(matrix, vector)

In [22]:
print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)

Матриця:
[[0.02825452 0.09385442 0.45281118]
 [0.32313234 0.76333876 0.71480036]]

Вектор:
[[9]
 [9]
 [1]]

Добуток матриці на вектор:
[[ 1.55179166]
 [10.49304028]]


12. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [23]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
sum_matrix = matrix1 + matrix2

print("Перша матриця:")
print(matrix1)

print("\nДруга матриця:")
print(matrix2)

print("\nСума матриць:")
print(sum_matrix)

Перша матриця:
[[4 7 6 9]
 [6 8 2 9]
 [7 6 9 6]
 [9 8 8 3]]

Друга матриця:
[[ 6 10  4  4]
 [10  8  4  1]
 [ 3  1  2  1]
 [ 1  5  2 10]]

Сума матриць:
[[10 17 10 13]
 [16 16  6 10]
 [10  7 11  7]
 [10 13 10 13]]


13. Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть їх добуток.

In [24]:
matrix1 = np.random.uniform(-1, 1, size=(4, 4))
matrix2 = np.random.uniform(-1, 1, size=(4, 4))
product = np.dot(matrix1, matrix2)

print("Перша матриця:")
print(matrix1)

print("\nДруга матриця:")
print(matrix2)

print("\nДобуток матриць:")
print(product)

Перша матриця:
[[ 0.57066306 -0.56009022  0.88659677 -0.53578223]
 [ 0.36463967 -0.13251448 -0.42126523  0.45105664]
 [ 0.99586069 -0.00193666 -0.95680613  0.36277273]
 [-0.34140593  0.15500513  0.24467682 -0.73281035]]

Друга матриця:
[[ 0.99342057  0.7861234  -0.38448527 -0.9446892 ]
 [ 0.37495481  0.56087848 -0.73997742  0.67525836]
 [-0.13013099 -0.85644052  0.48166287  0.42346434]
 [ 0.52625119 -0.91826122  0.67047398  0.17491963]]

Добуток матриць:
[[-0.04042985 -0.13286033  0.26285528 -0.63558154]
 [ 0.60474236  0.15892805  0.05737306 -0.53344481]
 [ 1.30400204  1.26811057 -0.59908899 -1.28380379]
 [-0.69852212  0.28191204 -0.35691328  0.40261999]]


14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму елементів матриці.

In [25]:
matrix = np.random.uniform(-1, 1, size=(3, 3))
sum_elements = np.sum(matrix)

print("Матриця:")
print(matrix)

print("\nСума елементів матриці:")
print(sum_elements)

Матриця:
[[ 0.2727468   0.11759341  0.52304004]
 [ 0.4489605   0.66319145 -0.59633796]
 [ 0.68710984 -0.04923371 -0.07469333]]

Сума елементів матриці:
1.9923770539929755


15. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [26]:
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Матриця:")
print(matrix)

print("\nВектор-стовпчик з сумами кожного рядка:")
print(row_sums)

Матриця:
[[-0.23647792 -0.23934428 -0.42374323  0.27477004  0.03867189]
 [ 0.12108617 -0.26805593 -0.4456711  -0.1770913   0.18123152]
 [ 0.28010537  0.10527834  0.13770997  0.16025027  0.06362124]
 [ 0.40246726  0.28249669  0.16215835  0.49147522 -0.47322152]
 [-0.17660934 -0.05036858  0.24260127 -0.18519158  0.259138  ]]

Вектор-стовпчик з сумами кожного рядка:
[[-0.5861235 ]
 [-0.58850064]
 [ 0.74696519]
 [ 0.865376  ]
 [ 0.08956976]]


**Висновки**

Під час виконання даної лабораторної роботи я пригадала як за допомогою модуля numpy створювати матриці і вектори, в тому числі з випадковими значеннями(з модулем random). A також як виконувати над ними основні операції: обчислення суми, різниці, добутку елементів,транспонування.